[ { created_at: 'Sun Jul 17 16:18:43 +0000 2016',
    id: 754711943353540600,
    id_str: '754711943353540609',
    text: 'RT @Gartner_inc: Gartner: #SmartMachines could remove offshoring as a competitive advantage https://t.co/UktkYHLhgl #GartnerSSVR https://t.…',
    truncated: false,
    entities:
     { hashtags: [Object],
       symbols: [],
       user_mentions: [Object],
       urls: [Object],
       media: [Object] },
    extended_entities: { media: [Object] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 3229401132,
       id_str: '3229401132',
       name: 'Watson Explorers',
       screen_name: 'WatsonExplorers',
       location: 'Fort Collins, CO',
       description: 'A group of northern Colorado technologists interested in IBM Watson and cognitive computing. Views expressed are ours alone and not anyone else.',
       url: 'http://t.co/JHLxofdYVC',
       entities: [Object],
       protected: false,
       followers_count: 23,
       friends_count: 102,
       listed_count: 0,
       created_at: 'Fri May 29 05:32:37 +0000 2015',
       favourites_count: 4,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 38,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/606572037167906816/9YSl2EDC_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/606572037167906816/9YSl2EDC_normal.png',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/3229401132/1433452896',
       profile_link_color: '0084B4',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Sun Jul 17 15:46:03 +0000 2016',
       id: 754703721456631800,
       id_str: '754703721456631809',
       text: 'Gartner: #SmartMachines could remove offshoring as a competitive advantage https://t.co/UktkYHLhgl #GartnerSSVR https://t.co/EDULWZ5M5W',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       source: '<a href="http://www.engage121.com" rel="nofollow">engage121</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 120,
       favorite_count: 79,
       favorited: false,
       retweeted: true,
       possibly_sensitive: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 120,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    possibly_sensitive: false,
    lang: 'en' } ]
RT @Gartner_inc: Gartner: #SmartMachines could remove offshoring as a competitive advantage https://t.co/UktkYHLhgl #GartnerSSVR https://t